USE [master]
GO

/****** Object:  Database [WebPage]    Script Date: 3/23/2020 4:53:15 PM ******/
CREATE DATABASE [WebPage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebPage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVEREXPRESS\MSSQL\DATA\WebPage.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WebPage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVEREXPRESS\MSSQL\DATA\WebPage_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WebPage] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebPage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebPage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebPage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebPage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebPage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebPage] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebPage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebPage] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WebPage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebPage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebPage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebPage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebPage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebPage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebPage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebPage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebPage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebPage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebPage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebPage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebPage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebPage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebPage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebPage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebPage] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebPage] SET  MULTI_USER 
GO

ALTER DATABASE [WebPage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebPage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebPage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebPage] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WebPage] SET  READ_WRITE 
GO


